/**
 * A Theme is a set of options that will be applied
 * ontop of the default values. see options.js for possible options
 */
import { Theme, WP, lightColors } from './settings/theme.js';

export default [
    Theme({
        name: 'Kitty Dark',
        icon: '󰄛',
        'desktop.wallpaper.img': WP + 'kittybl.jpeg',
    }),
    Theme({
        name: 'Kitty Light',
        icon: '󰄛',
        'desktop.wallpaper.img': WP + 'kitty.jpeg',
        ...lightColors,
        'theme.widget.bg': '$accent',
        'theme.widget.opacity': 64,
    }),
    Theme({
        name: 'Leaves',
        icon: '󰌪',
        'desktop.wallpaper.img': WP + 'leaves.jpg',
        'theme.accent.accent': '$green',
        'theme.accent.gradient': 'to right, $accent, darken($accent, 14%)',
        'theme.widget.opacity': 92,
        'border.opacity': 86,
        'theme.bg': 'transparentize(#171717, 0.3)',
        'bar.style': 'floating',
        'radii': 0,
    }),
    Theme({
        name: 'Ivory',
        icon: '󰟆',
        ...lightColors,
        'desktop.wallpaper.img': WP + 'ivory.png',
        'desktop.wallpaper.fg': '$bg_color',
        'desktop.screen_corners': false,
        'bar.style': 'separated',
        'theme.widget.bg': '$accent',
        'theme.widget.opacity': 64,
        'desktop.drop_shadow': false,
        'border.width': 2,
        'border.opacity': 0,
        'theme.accent.gradient': 'to right, $accent, darken($accent, 6%)',
        'hypr.inactive_border': 'rgba(111111FF)',
        'bar.separators': false,
    }),
    Theme({
        name: 'Space',
        icon: '',
        'desktop.wallpaper.img': WP + 'space.jpg',
        'spacing': 11,
        'padding': 10,
        'radii': 12,
        'theme.accent.accent': '$magenta',
        'desktop.screen_corners': false,
        'desktop.clock.enable': false,
        'bar.separators': false,
        'bar.icon': '',
        'theme.bg': 'transparentize(#171717, 0.3)',
        'theme.widget.opacity': 95,
        'bar.flat_buttons': false,
    }),
    Theme({
        name: 'Tokyo Night',
        icon: '🗼',
        'desktop.wallpaper.img': WP + 'market-garden.png',
        'spacing': 11,
        'padding': 10,
        'radii': 12,
        'color.red': '#f7768e',
        'color.green': '#9ece6a',
        'color.yellow': '#e0af68',
        'color.blue': '#7aa2f7',
        'color.magenta': '#bb9af7',
        'color.teal': '#7dcfff',
        'color.orange': '#ff9e64',
        'theme.bg': '#1a1b26',
        'theme.fg': '#a9b1d6',
        'theme.accent.fg': '#16161e',
        'theme.accent.accent': '$blue',
        'theme.accent.gradient': 'to left, $accent, darken($accent, 6%)',
        'desktop.screen_corners': false,
        'bar.separators': false,
    }),
    Theme({
        name: 'Catppuccin Latte',
        icon: '🌻',
        'desktop.wallpaper.img': WP + 'flood.jpg',
        'spacing': 11,
        'padding': 10,
        'radii': 12,
        'color.red': '#d20f39',
        'color.green': '#40a02b',
        'color.yellow': '#df8e1d',
        'color.blue': '#1e66f5',
        'color.magenta': '#ea76cb',
        'color.teal': '#179299',
        'color.orange': '#fe640b',
        'theme.scheme': 'light',
        'theme.bg': '#eff1f5',
        'theme.fg': '#4c4f69',
        'theme.accent.fg': '#ccd0da',
        'theme.accent.accent': '$blue',
        'theme.accent.gradient': '$accent',
        'theme.widget.bg': '$accent',
        'theme.widget.opacity': 64,
        'desktop.screen_corners': false,
        'bar.separators': false,
    }),
    Theme({
        name: 'Catppuccin Frappé',
        icon: '🪴',
        'desktop.wallpaper.img': WP + 'flood.jpg',
        'spacing': 11,
        'padding': 10,
        'radii': 12,
        'color.red': '#e78284',
        'color.green': '#a6d189',
        'color.yellow': '#e5c890',
        'color.blue': '#8caaee',
        'color.magenta': '#f4b8e4',
        'color.teal': '#81c8be',
        'color.orange': '#ef9f76',
        'theme.bg': '#303446',
        'theme.fg': '#c6d0f5',
        'theme.accent.fg': '#414559',
        'theme.accent.accent': '$blue',
        'theme.accent.gradient': '$accent',
        'desktop.screen_corners': false,
        'bar.separators': false,
    }),
    Theme({
        name: 'Catppuccin Macchiato',
        icon: '🌺',
        'desktop.wallpaper.img': WP + 'flood.jpg',
        'spacing': 11,
        'padding': 10,
        'radii': 12,
        'color.red': '#ed8796',
        'color.green': '#a6da95',
        'color.yellow': '#eed49f',
        'color.blue': '#8aadf4',
        'color.magenta': '#f5bde6',
        'color.teal': '#8bd5ca',
        'color.orange': '#f5a97f',
        'theme.bg': '#24273a',
        'theme.fg': '#cad3f5',
        'theme.accent.fg': '#363a4f',
        'theme.accent.accent': '$blue',
        'theme.accent.gradient': '$accent',
        'desktop.screen_corners': false,
        'bar.separators': false,
    }),
    Theme({
        name: 'Catppuccin Mocha',
        icon: '🌿',
        'desktop.wallpaper.img': WP + 'flood.jpg',
        'spacing': 11,
        'padding': 10,
        'radii': 12,
        'color.red': '#f38ba8',
        'color.green': '#a6e3a1',
        'color.yellow': '#f9e2af',
        'color.blue': '#89b4fa',
        'color.magenta': '#f5c2e7',
        'color.teal': '#94e2d5',
        'color.orange': '#fab387',
        'theme.bg': '#1e1e2e',
        'theme.fg': '#cdd6f4',
        'theme.accent.fg': '#313244',
        'theme.accent.accent': '$blue',
        'theme.accent.gradient': '$accent',
        'desktop.screen_corners': false,
        'bar.separators': false,
    }),
];
